# Generated by Django 5.1.2 on 2024-12-05 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='location.location')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'location'), name='unique_room_name_in_location')],
            },
        ),
    ]
